name: Test, Deploy and Tag

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pandas
            pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest
          flake8

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "py-churn-app-model"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            MONGO_USER
            MONGO_PASS
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}

      - name: Show Docker image size
        run: docker images py-churn-app-model
    
  tag: 
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        id: tag
        run: |
          TAG_NAME="deploy-$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag::$TAG_NAME"